apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  serviceSelector:
    matchLabels:
      expose: yes
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/nothing
        operator: DoesNotExist
  interfaces:
  - ^enxbc[0-9a-z]+
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  cidrs:
    - cidr: "192.168.1.240/28"