---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    routingMode: native
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
    bgp:
      enabled: false
    cluster:
      name: talos-cluster
      id: 1
    cni:
      exclusive: false
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
    ipam:
      mode: kubernetes
    k8sServiceHost: "192.168.1.151"
    k8sServicePort: 6443
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    kubeProxyReplacement: strict
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      # https://github.com/cilium/cilium/issues/26586
    l2announcements:
      enabled: true
      leaseDuration: 30s
      leaseRenewDeadline: 10s
      leaseRetryPeriod: 4s
    loadBalancer:
      algorithm: maglev
      mode: dsr
    securityContext:
      privileged: true
    tunnel: disabled